# Generated by Django 4.0.7 on 2023-04-04 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cnic',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, unique=True, verbose_name='CNIC number'),
            preserve_default=False,
        ),
    ]
