# Generated by Django 4.0.7 on 2023-04-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cnic',
            field=models.CharField(max_length=15, unique=True, verbose_name='CNIC number'),
        ),
    ]
