# Generated by Django 4.0.7 on 2023-04-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
